// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBooSbwpgxdkEVSkbYj2Pga0c3qZF9zAY8',
    appId: '1:84494797252:web:1afd8fafc7d9b644d1fc91',
    messagingSenderId: '84494797252',
    projectId: 'scoring-rooms',
    authDomain: 'scoring-rooms.firebaseapp.com',
    storageBucket: 'scoring-rooms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3PlfGUeerB53vQScx5y1y0oxQ8vQm3K8',
    appId: '1:84494797252:android:a1f611ddd4b9d765d1fc91',
    messagingSenderId: '84494797252',
    projectId: 'scoring-rooms',
    storageBucket: 'scoring-rooms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5y79XbtjpQFapcTl6-jvgNx5nKLeMvgM',
    appId: '1:84494797252:ios:35e2b98672a070c3d1fc91',
    messagingSenderId: '84494797252',
    projectId: 'scoring-rooms',
    storageBucket: 'scoring-rooms.firebasestorage.app',
    androidClientId: '84494797252-70pm3663oqh65rh6r4972q2fl8fm5l7e.apps.googleusercontent.com',
    iosClientId: '84494797252-shm603jq363msjdjd7rpma3d24rubieu.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoringRooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5y79XbtjpQFapcTl6-jvgNx5nKLeMvgM',
    appId: '1:84494797252:ios:35e2b98672a070c3d1fc91',
    messagingSenderId: '84494797252',
    projectId: 'scoring-rooms',
    storageBucket: 'scoring-rooms.firebasestorage.app',
    androidClientId: '84494797252-70pm3663oqh65rh6r4972q2fl8fm5l7e.apps.googleusercontent.com',
    iosClientId: '84494797252-shm603jq363msjdjd7rpma3d24rubieu.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoringRooms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBooSbwpgxdkEVSkbYj2Pga0c3qZF9zAY8',
    appId: '1:84494797252:web:ac05a7b435186715d1fc91',
    messagingSenderId: '84494797252',
    projectId: 'scoring-rooms',
    authDomain: 'scoring-rooms.firebaseapp.com',
    storageBucket: 'scoring-rooms.firebasestorage.app',
  );

}